### ISSUE TITLE
ion resolve prints some fields as [Object] rather than as JSON

### ISSUE THREAD

**Issue by markwahl-msft** [decentralized-identity/ion-cli#4]
A run of `ion resolve did:ion:EiB...` retrieves but leaves out interesting parts of the retrieved document, with `[Object]` in a few places instead of showing the actual fields.

```
{
  '@context': 'https://w3id.org/did-resolution/v1',
  didDocument: {
    id: 'did:ion:EiB...',
    '@context': [ 'https://www.w3.org/ns/did/v1', [Object] ],
    service: [ [Object] ],
    verificationMethod: [ [Object] ], ...
```    

Maybe `console.log(didDocument);` is not the best way to render this?  Perhaps instead
`console.log(JSON.stringify(didDocument));`

**Comment by codeglobally** [comment]
This has been fixed in 0.3.0. See [Output](https://github.com/decentralized-identity/ion-cli/blob/main/src/Output.ts) class.
